import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  PORT: Joi.number().default(3001),
  CORS_ALLOWED_ORIGINS: Joi.string().default('http://localhost:3000'),
  APP_WEB_URL: Joi.string().uri().default('http://localhost:3000'),
  JWT_SECRET: Joi.string().min(16).default('ultra-secret-key'),
  JWT_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_SECRET: Joi.string().min(16).default('ultra-refresh-secret'),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('7d'),
  MEDIA_BASE_URL: Joi.string().uri().default('http://localhost:3001'),
  MEDIA_UPLOAD_DIR: Joi.string().default('uploads/media'),
  CERTIFICATE_SIGNATURE: Joi.string().default(
    'Empowering lifelong learners — Officially certified by ULearner',
  ),
  ADMIN_EMAIL: Joi.string().email().default('admin@ulearner.dev'),
  ADMIN_PASSWORD: Joi.string().min(8).default('change-me-now'),
  ADMIN_COOKIE_NAME: Joi.string().default('ulearner_admin'),
  ADMIN_COOKIE_SECRET: Joi.string().min(12).default('super-secret-admin-cookie'),
  MAIL_FROM_EMAIL: Joi.string().email().default('notifications.ulearner@gmail.com'),
  MAIL_FROM_NAME: Joi.string().default('ULearner'),
  SMTP_HOST: Joi.string().optional(),
  SMTP_PORT: Joi.number().optional(),
  SMTP_SECURE: Joi.boolean().default(false),
  SMTP_USER: Joi.string().optional(),
  SMTP_PASSWORD: Joi.string().optional(),
  POSTGRES_HOST: Joi.string().default('localhost'),
  POSTGRES_PORT: Joi.number().default(5432),
  POSTGRES_DB: Joi.string().default('ulearner'),
  POSTGRES_USER: Joi.string().default('potgress'),
  POSTGRES_PASSWORD: Joi.string().default('29082006'),
  DATABASE_LOGGING: Joi.boolean().default(false),
});
